[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mooper"
version = "0.1.0"
description = "A lightweight, low-resource-friendly file conversion utility"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
authors = [
  {name = "forex911"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Multimedia :: Video :: Conversion",
    "Topic :: Multimedia :: Sound/Audio :: Conversion",
]
dependencies = [
    "pillow",
    "av",
    "questionary",
    "tqdm",
    "rich",
]

[project.optional-dependencies]
dev = [
    "pytest",
]

[project.scripts]
mooper = "mooper.cli:main"

[tool.setuptools.package-data]
mooper = ["README.md"]
